# Generated by Django 3.2.9 on 2022-02-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Название категори', 'verbose_name_plural': 'Название категории'},
        ),
    ]
