# Generated by Django 3.2.9 on 2022-02-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория блюд', 'verbose_name_plural': 'Категории блюды'},
        ),
    ]
